name: Build Sphinx

# execute this workflow automatically when a we push to master
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
